#!/usr/bin/env python3
"""Create a minimal local DeerFlow demo configuration."""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class BootstrapResult:
    relative_path: str
    status: str


def bootstrap_demo(project_root: Path | str, *, force: bool = False) -> list[BootstrapResult]:
    root = Path(project_root).resolve()
    root.mkdir(parents=True, exist_ok=True)

    config_version = _read_config_version(root / "config.example.yaml")
    files = {
        "config.yaml": _build_config_yaml(config_version),
        ".env": _build_env_file(),
        "frontend/.env": _build_frontend_env_file(),
        "extensions_config.json": _json({"mcpServers": {}, "skills": {}}),
        "registries/demo_extensions.json": _json(_demo_registry()),
    }

    results: list[BootstrapResult] = []
    for relative_path, content in files.items():
        target = root / relative_path
        if target.exists() and not force:
            results.append(BootstrapResult(relative_path, "skipped"))
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        results.append(BootstrapResult(relative_path, "written"))
    return results


def _read_config_version(example_path: Path) -> int:
    if not example_path.exists():
        return 15
    match = re.search(r"^config_version:\s*(\d+)\s*$", example_path.read_text(encoding="utf-8"), re.MULTILINE)
    return int(match.group(1)) if match else 15


def _build_config_yaml(config_version: int) -> str:
    return f"""# Minimal local demo configuration generated by scripts/bootstrap_demo.py.
# Run `make doctor` after adding a real LLM key to .env.
config_version: {config_version}
log_level: info

token_usage:
  enabled: true

models:
  - name: demo-gpt-4o-mini
    display_name: Demo GPT-4o mini
    use: langchain_openai:ChatOpenAI
    model: gpt-4o-mini
    request_timeout: 120.0
    max_retries: 2
    max_tokens: 4096
    temperature: 0.2
    supports_vision: true

sandbox:
  use: deerflow.sandbox.local:LocalSandboxProvider
  allow_host_bash: false

tools:
  - name: web_search
    group: search
    use: deerflow.community.ddg_search.tools:web_search_tool
  - name: web_fetch
    group: search
    use: deerflow.community.jina_ai.tools:web_fetch_tool

tool_groups:
  - name: search
  - name: reporting

tool_search:
  enabled: true

database:
  backend: sqlite
  sqlite_dir: .deer-flow/data

run_events:
  backend: memory
  max_trace_content: 10240
  track_token_usage: true

memory:
  enabled: false

agents_api:
  enabled: false

skill_evolution:
  enabled: false
"""


def _build_env_file() -> str:
    return """# DeerFlow local demo environment.
# Add a real key before sending chat requests to the configured OpenAI model.
# OPENAI_API_KEY=sk-your-key

# Keep local extension packages and registries rooted at this checkout.
DEER_FLOW_EXTENSION_MANIFESTS=registries/demo_extensions.json
DEER_FLOW_EXTENSIONS_CONFIG_PATH=extensions_config.json

# Optional direct Gateway wiring. Defaults match make dev.
# DEER_FLOW_INTERNAL_GATEWAY_BASE_URL=http://localhost:8001
# DEER_FLOW_TRUSTED_ORIGINS=http://localhost:3000,http://localhost:2026
"""


def _build_frontend_env_file() -> str:
    return """# DeerFlow frontend local demo environment.
# Leave unset to use Next.js rewrites through the local Gateway.
# NEXT_PUBLIC_BACKEND_BASE_URL=http://localhost:8001
# NEXT_PUBLIC_LANGGRAPH_BASE_URL=http://localhost:8001/api
"""


def _demo_registry() -> dict:
    return {
        "version": 1,
        "imports": [
            {"name": "internal-agents", "kind": "agent", "type": "directory", "path": "internal_agents"},
            {"name": "internal-mcps", "kind": "mcp", "type": "directory", "path": "internal_mcps"},
            {"name": "internal-tools", "kind": "tool", "type": "directory", "path": "internal_tools"},
            {"name": "internal-skills", "kind": "skill", "type": "directory", "path": "internal_skills"},
        ],
        "extensions": [
            {
                "kind": "agent",
                "name": "reporting-agent",
                "enabled": True,
                "source": "local",
                "description": "Generate internal reports and exports from structured business data",
                "display_name": "Reporting Agent",
                "category": "Reporting",
                "metadata": {
                    "tool_groups": ["reporting"],
                    "skills": [],
                    "soul": "You are an internal reporting specialist. Produce concise, auditable reports and prefer generated artifacts when the user asks for deliverables.",
                },
            },
            {
                "kind": "tool",
                "name": "html-report",
                "enabled": True,
                "source": "local",
                "entrypoint": "internal_tools.reporting:html_report",
                "description": "Generate a self-contained HTML report artifact",
                "tags": ["reporting", "artifact"],
                "risk_level": "low",
                "display_name": "HTML Report",
                "category": "Reporting",
                "metadata": {"group": "reporting"},
            },
            {
                "kind": "tool",
                "name": "csv-export",
                "enabled": True,
                "source": "local",
                "entrypoint": "internal_tools.reporting:csv_export",
                "description": "Generate a CSV artifact from structured JSON rows",
                "tags": ["reporting", "data"],
                "risk_level": "low",
                "display_name": "CSV Export",
                "category": "Reporting",
                "metadata": {"group": "reporting"},
            },
            {
                "kind": "mcp",
                "name": "local-docs",
                "enabled": False,
                "source": "local",
                "description": "Example stdio MCP server descriptor for internal documentation search",
                "display_name": "Local Docs MCP",
                "category": "Knowledge",
                "metadata": {
                    "type": "stdio",
                    "command": "python",
                    "args": ["-m", "internal_mcps.local_docs"],
                    "env": {"DOCS_ROOT": "$DOCS_ROOT"},
                },
            },
            {
                "kind": "skill",
                "name": "market-research",
                "enabled": False,
                "source": "local",
                "entrypoint": "internal_skills/market-research",
                "description": "Research market context from approved sources",
                "allowed_tools": ["web_search", "html_report", "csv_export"],
                "tags": ["research"],
                "risk_level": "medium",
                "display_name": "Market Research",
                "category": "Research",
            },
        ],
    }


def _json(data: dict) -> str:
    return json.dumps(data, indent=2) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Create minimal local demo config files.")
    parser.add_argument("--project-root", default=Path(__file__).resolve().parents[1], type=Path)
    parser.add_argument("--force", action="store_true", help="Overwrite existing generated files.")
    args = parser.parse_args(argv)

    results = bootstrap_demo(args.project_root, force=args.force)
    for result in results:
        marker = "wrote" if result.status == "written" else "kept"
        print(f"{marker}: {result.relative_path}")
    print("")
    print("Next:")
    print("  1. Add OPENAI_API_KEY to .env")
    print("  2. Run make doctor")
    print("  3. Run make dev")
    return 0


if __name__ == "__main__":
    sys.exit(main())
